name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker image build
        run: docker build -t wodus5677/collaberr-web .

      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: tag docker image
        run: docker image tag wodus5677/collaberr-web:app wodus5677/collaberr-web:app

      - name: docker hub push
        run: docker push wodus5677/collaberr-web:app
